### ISSUE TITLE
Second event at same date not displayed

### ISSUE THREAD

**Issue by djahnie** [kanthaus/kanthaus.online#9]
We have the fsww hackweek starting 2018-02-24.

Now I added the KifA at the same date and the event...
- does not show up in the event list (https://kanthaus.online/events)
- is not accessible via direct link (https://kanthaus.online/events/2018-02-24_KifA)

[This is my commit](https://github.com/kanthaus/kanthaus.online/commit/0f6be30c33d8f6d22ccbe9724b8bb7a45e8720bc).

Help..?! 😭

**Comment by tiltec** [comment]
Wrote a comment :)

**Comment by djahnie** [comment]
I tested changing the date:
2018-02-23 worked, 2018-02-25 didn't. And interestingly _no date after the 23rd worked_, I tried out a handful. Past dates did work. Tomorrow worked as well - even though it's at the same time as the building week. This means it has nothing to do with having mutiple events at the same time.

Now I understand it even less... -.-

**Comment by djahnie** [comment]
New theory: It's because of pagination. For some reason the event page shows only 5 events in the future.
Also, when going through the events one by one using the buttons on thr bottom, the KifA _is_ accessible. I just got the link wrong before... 😅 

This is the right one: https://kanthaus.online/events/2018-02-24_kifa (capitalization is a bitch...)

**Comment by tiltec** [comment]
Had to change the sorting direction when creating the original collection in the YAML. There's another problem that could occur now: when we have more than 10 upcoming events at same time, then the most recent one wouldn't get shown. I would propose to increase the pagination size from 10 to 20 as mitigation.
